weights: ['weights/l6_all_last.pt',
          'weights/x6_neck-det_last.pt']
path: '/home/agc2021/dataset'

names: ['c_1', 'c_2', 'c_3', 'c_4', 'c_5', 'c_6', 'c_7']

imgsz: 1280 # train img size
batchsz: 4
numworker: 4
conf: 0.6
iou: 0.8
max-det: 140 # 7 * 20 (class_num * max_object_num)

tta-conf: 0.4
# TTA_AUG_LIST = [
#     oda.Rotate90Left(),
#     oda.Rotate90Right(),
#     oda.HorizontalFlip(),
#     oda.VerticalFlip(),
#     oda.RandColorJitter(),
#     oda.TorchBlur(),
#     oda.TorchMedianBlur()
# ]
tta-aug: [2] # index of tta-aug-list
tta-scale: [1]

outbound: 20 # pixel num from edges
bbox-filter: True 
bbox-over: 0.3 # ratio to img size
bbox-under: 128 # num to divide h or w

agnostic-nms: False
tta: True
half: True
fuse: False
