weights: ['weights/s6_neck-det_best.pt']
path: '/home/agc2021/dataset/'

names: ['c_1', 'c_2', 'c_3', 'c_4', 'c_5', 'c_6', 'c_7']

imgsz: 1280
batchsz: 4
numworker: 4
conf: 0.6
iou: 0.8
max-det: 30
# 140 # 7 * 20 (class_num * max_object_num)

tta-conf: 0.4
# TTA_AUG_LIST = [oda.Rotate90Left(), oda.Rotate90Right(),
#                 oda.HorizontalFlip(), oda.VerticalFlip(),
#                 oda.Multiply(0.9), oda.Multiply(1.1),
#                 oda.RandColorJitter(),
#                 oda.Blur(), oda.MotionBlur(), oda.MedianBlur()]
tta-aug: [0,1] # index of tta-aug-list
tta-scale: [1, 1.3, 1.5]

outbound: 20 # pixel
bbox-over: 0.3
bbox-under: 32

agnostic-nms: False
tta: True
half: True
fuse: False
